name: "Nacho SKIP"
branding:
  icon: "compass"
  color: "blue"
description: "A composite GitHub Action for authenticating with Kartverket and SKIP when using NAIS's salsa action for image provenance."
inputs:
  auth_project_number:
    description: "The GCP Project Number used for authentication. A 12-digit number used as a unique identifier for the project. Used to find workload identity pool."
    required: true
  service_account:
    description: "The GCP service account connected to the identity pool that will be used to authenticate with GCP."
    required: true
  image_name:
    description: "Image name of the image to sign. In the format <REGISTRY>/<FOLDER>/<NAME>, where <FOLDER> is optional. Example: `ghcr.io/kartverket/skip`"
    required: true
  image_digest:
    description: "Image digest of the image to sign. Looks like `sha256:a428de44a9059f31a59237a5881c2d2cffa93757d99026156e4ea544577ab7f3`."
    required: true
  image_registry:
    description: "Registry in which the image is created. Defaults to `ghcr.io`, GitHubs registry."
    required: false
    default: "ghcr.io"
  workload_identity_provider_override:
    description: "The ID of the provider to use for authentication. Only used for overriding the default workload identity provider based on project number. It should be in the format of `projects/{{project}}/locations/global/workloadIdentityPools/{{workload_identity_pool_id}}/providers/{{workload_identity_pool_provider_id}}`"
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - run: |
        PRODUCT_NAME=$(echo ${{ inputs.service_account }} | sed 's/-deploy.*//')
        DEFAULT_WORKLOAD_IDENTITY="projects/${{ inputs.auth_project_number }}/locations/global/workloadIdentityPools/$PRODUCT_NAME-deploy-pool/providers/github-provider"
        OVERRIDE=${{ inputs.workload_identity_provider_override }}
        PROVIDER=${OVERRIDE:-$DEFAULT_WORKLOAD_IDENTITY}
        echo "WORKLOAD_IDENTITY_PROVIDER=$PROVIDER" >> $GITHUB_OUTPUT
      shell: bash
      id: set_wip
      name: Set Workload Identity Provider

    - uses: google-github-actions/auth@v1
      id: google_auth
      name: Authenticate With Google
      with:
        workload_identity_provider: ${{ steps.set_wip.outputs.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ inputs.service_account }}
        token_format: "id_token"
        id_token_audience: sigstore
        id_token_include_email: true

    - uses: anderssonw/salsa@action-optional-verify
      with:
        image: ${{ inputs.image_name }}
        image_digest: ${{ inputs.image_digest }}
        key: gcpkms://projects/skip-sandbox-37c2/locations/europe/keyRings/test-ring/cryptoKeys/salsa-test-key
        identity_token: ${{ steps.google_auth.outputs.id_token }}
        registry: ${{ inputs.image_registry }}
      env:
        COSIGN_EXPERIMENTAL: "true"
